// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package xvault

import (
	"log"

	"github.com/sandwich-go/xconf"
	"github.com/sandwich-go/xconf-providers/status"
	"github.com/sandwich-go/xconf/kv"
)

// Options should use NewOptions to initialize it
type Options struct {
	Address         string // Vault地址，例如：http://localhost:8200
	Token           string // Token认证方式使用的token
	Role            string // Kubernetes认证方式使用的role
	ServiceAccount  string // K8s ServiceAccount token路径
	KubernetesMount string // Kubernetes认证挂载点
	SecretMount     string // secret引擎
	AutoDetectEnv   bool   // 是否自动检测环境（K8s或本地）
	KVOption        []kv.Option
	LogDebug        xconf.LogFunc
	LogWarning      xconf.LogFunc
	OnUpdate        status.OnConfUpdate
}

// NewOptions new Options
func NewOptions(opts ...Option) *Options {
	cc := newDefaultOptions()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *Options) ApplyOption(opts ...Option) {
	for _, opt := range opts {
		opt.Apply(cc)
	}
}

// OptionFunc option func
type Option interface {
	Apply(cc *Options)
}

var _ Option = OptionFunc(nil)

type OptionFunc func(cc *Options)

func (f OptionFunc) Apply(cc *Options) {
	f(cc)
}

// WithAddress option func for filed Address
func WithAddress(v string) OptionFunc {
	return func(cc *Options) {
		cc.Address = v
	}
}

// WithToken option func for filed Token
func WithToken(v string) OptionFunc {
	return func(cc *Options) {
		cc.Token = v
	}
}

// WithRole option func for filed Role
func WithRole(v string) OptionFunc {
	return func(cc *Options) {
		cc.Role = v
	}
}

// WithServiceAccount option func for filed ServiceAccount
func WithServiceAccount(v string) OptionFunc {
	return func(cc *Options) {
		cc.ServiceAccount = v
	}
}

// WithKubernetesMount option func for filed KubernetesMount
func WithKubernetesMount(v string) OptionFunc {
	return func(cc *Options) {
		cc.KubernetesMount = v
	}
}

// WithSecretMount option func for filed SecretMount
func WithSecretMount(v string) OptionFunc {
	return func(cc *Options) {
		cc.SecretMount = v
	}
}

// WithAutoDetectEnv option func for filed AutoDetectEnv
func WithAutoDetectEnv(v bool) OptionFunc {
	return func(cc *Options) {
		cc.AutoDetectEnv = v
	}
}

// WithKVOption option func for filed KVOption
func WithKVOption(v ...kv.Option) OptionFunc {
	return func(cc *Options) {
		cc.KVOption = v
	}
}

// AppendKVOption append func for filed KVOption
func AppendKVOption(v ...kv.Option) OptionFunc {
	return func(cc *Options) {
		cc.KVOption = append(cc.KVOption, v...)
	}
}

// WithLogDebug option func for filed LogDebug
func WithLogDebug(v xconf.LogFunc) OptionFunc {
	return func(cc *Options) {
		cc.LogDebug = v
	}
}

// WithLogWarning option func for filed LogWarning
func WithLogWarning(v xconf.LogFunc) OptionFunc {
	return func(cc *Options) {
		cc.LogWarning = v
	}
}

// WithOnUpdate option func for filed OnUpdate
func WithOnUpdate(v status.OnConfUpdate) OptionFunc {
	return func(cc *Options) {
		cc.OnUpdate = v
	}
}

// InstallOptionsWatchDog the installed func will called when NewOptions  called
func InstallOptionsWatchDog(dog func(cc *Options)) { watchDogOptions = dog }

// watchDogOptions global watch dog
var watchDogOptions func(cc *Options)

// setOptionsDefaultValue default Options value
func setOptionsDefaultValue(cc *Options) {
	for _, opt := range [...]OptionFunc{
		WithAddress(""),
		WithToken(""),
		WithRole(""),
		WithServiceAccount("/var/run/secrets/kubernetes.io/serviceaccount/token"),
		WithKubernetesMount("kubernetes"),
		WithSecretMount("secret"),
		WithAutoDetectEnv(true),
		WithKVOption(nil...),
		WithLogDebug(func(s string) { log.Println("[  DEBUG] " + s) }),
		WithLogWarning(func(s string) { log.Println("[WARNING] " + s) }),
		WithOnUpdate(status.LastStatus.UpdateConf),
	} {
		opt(cc)
	}
}

// newDefaultOptions new default Options
func newDefaultOptions() *Options {
	cc := &Options{}
	setOptionsDefaultValue(cc)
	return cc
}

// all getter func
func (cc *Options) GetAddress() string               { return cc.Address }
func (cc *Options) GetToken() string                 { return cc.Token }
func (cc *Options) GetRole() string                  { return cc.Role }
func (cc *Options) GetServiceAccount() string        { return cc.ServiceAccount }
func (cc *Options) GetKubernetesMount() string       { return cc.KubernetesMount }
func (cc *Options) GetSecretMount() string           { return cc.SecretMount }
func (cc *Options) GetAutoDetectEnv() bool           { return cc.AutoDetectEnv }
func (cc *Options) GetKVOption() []kv.Option         { return cc.KVOption }
func (cc *Options) GetLogDebug() xconf.LogFunc       { return cc.LogDebug }
func (cc *Options) GetLogWarning() xconf.LogFunc     { return cc.LogWarning }
func (cc *Options) GetOnUpdate() status.OnConfUpdate { return cc.OnUpdate }

// OptionsVisitor visitor interface for Options
type OptionsVisitor interface {
	GetAddress() string
	GetToken() string
	GetRole() string
	GetServiceAccount() string
	GetKubernetesMount() string
	GetSecretMount() string
	GetAutoDetectEnv() bool
	GetKVOption() []kv.Option
	GetLogDebug() xconf.LogFunc
	GetLogWarning() xconf.LogFunc
	GetOnUpdate() status.OnConfUpdate
}

// OptionsInterface visitor + ApplyOption interface for Options
type OptionsInterface interface {
	OptionsVisitor
	ApplyOption(...Option)
}
